//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPractice.AppConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.MaterialsToBuy = new HashSet<MaterialsToBuy>();
        }
    
        public int ID { get; set; }
        public int IDClinet { get; set; }
        public int IDUser { get; set; }
        public int IDTypeTechnic { get; set; }
        public string Technic { get; set; }
        public string Description { get; set; }
        public string IsPayed { get; set; }
        public System.DateTime DateOfStart { get; set; }
        public Nullable<System.DateTime> DateOfEnd { get; set; }
        public int IDStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeTechnic TypeTechnic { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsToBuy> MaterialsToBuy { get; set; }
    }
}
